### ISSUE TITLE
failed to initialize vulnerable driver

### ISSUE THREAD

**Issue by nullcult** [zer0condition/mhydeath#1]
Hi, am trying this out with kaspersky but getting the error:
` failed to initialize vulnerable driver`

What could I be missing

**Comment by zer0condition** [comment]
Are you running as admin

**Comment by nullcult** [comment]
Yes, nt/system

**Comment by zer0condition** [comment]
No idea, probably blocked by kaspersky

**Comment by crypt0n-root** [comment]
as I noticed this bypass does not work on behalf of nt\authority SYSTEM but only on behalf of the administrator
