### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by marknsec** [zer0condition/mhydeath#2]
Hello,
In Demo it shows mhydeath exe file. 
But if we download zip file it does not show :) Tried running main.cpp 
In file included from main.cpp:2:0:
mhyprotect/mhyprotect.h:4:22: fatal error: filesystem: No such file or directory
 #include <filesystem>
                      ^
compilation terminated.

**Comment by zer0condition** [comment]
#include "mhyprotect/mhyprotect.h"

**Comment by marknsec** [comment]
mhyprotect/mhyprotect.h this file exist in same folder. Still script is giving error
